# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'excel2ppt_qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from readExcelClass import ReadExcelClass
from budgetClass import BudgetClass
from thinkcellClass import ThinkcellClass
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QLineEdit, QVBoxLayout, QWidget, QFileDialog
from exception_handler import exception_signal_instance


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 400))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 400))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        MainWindow.setFont(font)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/10692.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-image: url(:/background/white-concrete-wall.jpg);\n"
                                 "background-color: rgba(0,0,0,0);")
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
                                      "    border: 2px solid #808080;\n"
                                      "    border-radius: 5px;\n"
                                      "    padding: 5px;\n"
                                      "    background-color: #f0f0f0;\n"
                                      "    selection-color: white;\n"
                                      "    selection-background-color:#5CACEE;\n"
                                      "}")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("\n"
                                        "QPushButton {\n"
                                        "    background-color: #FF0000 !important;\n"
                                        "    border: 2px solid #FF0000;\n"
                                        "    color: black;\n"
                                        "    padding: 10px 20px;\n"
                                        "    border-radius: 5px;\n"
                                        "    font-weight: bold;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: #FF3333 !important;\n"
                                        "    border-color: #FF3333;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    background-color: #CC0000 !important;\n"
                                        "    border-color: #CC0000;\n"
                                        "}")
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
                                    "    border: 2px solid #808080;\n"
                                    "    border-radius: 5px;\n"
                                    "    padding: 5px;\n"
                                    "    background-color: #f0f0f0;\n"
                                    "    selection-color: white;\n"
                                    "    selection-background-color:#5CACEE;\n"
                                    "}")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("\n"
                                      "QPushButton {\n"
                                      "    background-color: #FF0000;\n"
                                      "    border: 2px solid #FF0000;\n"
                                      "    color: black;\n"
                                      "    padding: 10px 20px;\n"
                                      "    border-radius: 5px;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: #FF3333;\n"
                                      "    border-color: #FF3333;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: #CC0000;\n"
                                      "    border-color: #CC0000;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("\n"
                                        "QPushButton {\n"
                                        "    background-color: #FFA500;\n"
                                        "    border: 2px solid #FFA500;\n"
                                        "    color: black;\n"
                                        "    padding: 10px 20px;\n"
                                        "    border-radius: 5px;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover {\n"
                                        "    background-color: #FFC04D;\n"
                                        "    border-color: #FFC04D;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed {\n"
                                        "    background-color: #FF8500;\n"
                                        "    border-color: #FF8500;\n"
                                        "}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.statusbar.setFont(font)
        self.statusbar.setMouseTracking(False)
        self.statusbar.setTabletTracking(False)
        self.statusbar.setAcceptDrops(True)
        self.statusbar.setStyleSheet("color: red;")
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_3.clicked.connect(self.excel2ppt_on_button_clicked)  # type: ignore
        self.pushButton.clicked.connect(self.excel_on_button_clicked)  # type: ignore
        self.pushButton_2.clicked.connect(self.ppt_on_button_clicked)  # type: ignore
        exception_signal_instance.signal.connect(self.update_status_bar)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Tools to convert excel to PowerPoint"))
        self.pushButton_2.setText(_translate("MainWindow", "Choose PPT Template File"))
        self.pushButton.setText(_translate("MainWindow", "Choose Excel Template File"))
        self.pushButton_3.setText(_translate("MainWindow", "excel2ppt"))

    def excel_on_button_clicked(self):
        options = QFileDialog.Options()
        file_name, _ = QFileDialog.getOpenFileName(QMainWindow(), "Select File", "",
                                                   "All Files (*);;Text Files (*.txt)",
                                                   options=options)
        if file_name:
            self.lineEdit.setText(file_name)
            self.statusbar.showMessage("excel template file path: " + file_name, 5000)

    def excel2ppt_on_button_clicked(self):
        content1 = self.lineEdit.text()
        content2 = self.lineEdit_2.text()

        if not content1 and content2:
            self.statusbar.showMessage("Pls select the excel Template file!", 5000)
        elif content1 and not content2:
            self.statusbar.showMessage("Pls select the ppt Template file!", 5000)
        elif not content1 and not content2:
            self.statusbar.showMessage("Pls select the excel and ppt Template file!", 5000)
        else:
            content1 = content1.replace('/', '\\')
            content2 = content2.replace('/', '\\')
            df_class = ReadExcelClass(content1)
            df_class.read_excel_file()



            budget_class = BudgetClass(df_class)
            budget_class.get_monthly_budget()

            thinkcell_class = ThinkcellClass(content2, budget_class)
            thinkcell_class.add_template()
            thinkcell_class.add_chart()
            thinkcell_class.save_file()
            self.statusbar.showMessage("ppt created successfully! file path: " + thinkcell_class.filename, 5000)

    def ppt_on_button_clicked(self):
        options = QFileDialog.Options()
        file_name, _ = QFileDialog.getOpenFileName(QMainWindow(), "Select File", "",
                                                   "All Files (*);;Text Files (*.txt)",
                                                   options=options)
        if file_name:
            self.lineEdit_2.setText(file_name)
            self.statusbar.showMessage("excel template file path: " + file_name, 5000)

    def update_status_bar(self, error_message):
        self.statusbar.showMessage(f'Error: {error_message}', 5000)

import pictures_rc


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'excel2ppt_qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QFileDialog

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 400)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 400))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 400))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        MainWindow.setFont(font)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/10692.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-image: url(:/background/white-concrete-wall.jpg);\n"
"background-color: rgba(0,0,0,0);")
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(238, 65, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #FFA500;\n"
"    border: 2px solid #FFA500;\n"
"    color: black;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFC04D;\n"
"    border-color: #FFC04D;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FF8500;\n"
"    border-color: #FF8500;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #808080;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #f0f0f0;\n"
"    selection-color: white;\n"
"    selection-background-color:#5CACEE;\n"
"}")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #FF0000;\n"
"    border: 2px solid #FF0000;\n"
"    color: black;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FF3333;\n"
"    border-color: #FF3333;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #CC0000;\n"
"    border-color: #CC0000;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #808080;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #f0f0f0;\n"
"    selection-color: white;\n"
"    selection-background-color:#5CACEE;\n"
"}")
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #FF0000 !important;\n"
"    border: 2px solid #FF0000;\n"
"    color: black;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FF3333 !important;\n"
"    border-color: #FF3333;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #CC0000 !important;\n"
"    border-color: #CC0000;\n"
"}")
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(278, 65, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(168, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem4, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #808080;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #f0f0f0;\n"
"    selection-color: white;\n"
"    selection-background-color:#5CACEE;\n"
"}")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #FF0000 !important;\n"
"    border: 2px solid #FF0000;\n"
"    color: black;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FF3333 !important;\n"
"    border-color: #FF3333;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #CC0000 !important;\n"
"    border-color: #CC0000;\n"
"}")
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(168, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem5, 2, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #808080;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #f0f0f0;\n"
"    selection-color: white;\n"
"    selection-background-color:#5CACEE;\n"
"}")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_4.addWidget(self.lineEdit_4, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setAutoFillBackground(False)
        self.pushButton_5.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #FF0000 !important;\n"
"    border: 2px solid #FF0000;\n"
"    color: black;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FF3333 !important;\n"
"    border-color: #FF3333;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #CC0000 !important;\n"
"    border-color: #CC0000;\n"
"}")
        self.pushButton_5.setAutoDefault(False)
        self.pushButton_5.setDefault(False)
        self.pushButton_5.setFlat(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_4.addWidget(self.pushButton_5, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 3, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(168, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem6, 4, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #808080;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: #f0f0f0;\n"
"    selection-color: white;\n"
"    selection-background-color:#5CACEE;\n"
"}")
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_5.addWidget(self.lineEdit_5, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setAutoFillBackground(False)
        self.pushButton_6.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #FF0000 !important;\n"
"    border: 2px solid #FF0000;\n"
"    color: black;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FF3333 !important;\n"
"    border-color: #FF3333;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #CC0000 !important;\n"
"    border-color: #CC0000;\n"
"}")
        self.pushButton_6.setAutoDefault(False)
        self.pushButton_6.setDefault(False)
        self.pushButton_6.setFlat(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_5.addWidget(self.pushButton_6, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 5, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(168, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem7, 6, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: #FFA500;\n"
"    border: 2px solid #FFA500;\n"
"    color: black;\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #FFC04D;\n"
"    border-color: #FFC04D;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #FF8500;\n"
"    border-color: #FF8500;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_4.addWidget(self.pushButton_7)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem9)
        self.gridLayout_6.addLayout(self.horizontalLayout_4, 7, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_7.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Audi Type")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.statusbar.setFont(font)
        self.statusbar.setMouseTracking(False)
        self.statusbar.setTabletTracking(False)
        self.statusbar.setAcceptDrops(True)
        self.statusbar.setStyleSheet("color: red;")
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.pushButton_2.clicked.connect(self.file_select_button_clicked) # type: ignore
        self.pushButton.clicked.connect(self.file_select_button_clicked) # type: ignore
        self.pushButton_3.clicked.connect(self.gti2tax_on_button_clicked) # type: ignore
        self.pushButton_4.clicked.connect(self.file_select_button_clicked) # type: ignore
        self.pushButton_5.clicked.connect(self.file_select_button_clicked) # type: ignore
        self.pushButton_6.clicked.connect(self.file_select_button_clicked) # type: ignore
        self.pushButton_7.clicked.connect(self.tax2gti_on_button_clicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Excel Converter for Invoice"))
        self.label.setText(_translate("MainWindow", "Excel Converter for Invoice"))
        self.pushButton_3.setText(_translate("MainWindow", "GTI -> Tax"))
        self.pushButton.setText(_translate("MainWindow", "Choose Tax Template File"))
        self.pushButton_2.setText(_translate("MainWindow", "Choose file from GTI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "GTI --> Tax"))
        self.pushButton_4.setText(_translate("MainWindow", "Choose file from GTI"))
        self.pushButton_5.setText(_translate("MainWindow", "Choose file from Tax"))
        self.pushButton_6.setText(_translate("MainWindow", "Choose file 3"))
        self.pushButton_7.setText(_translate("MainWindow", "Tax -> GTI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "GTI <-- Tax"))

    def file_select_button_clicked(self):
        options = QFileDialog.Options()
        file_name, _ = QFileDialog.getOpenFileName(QMainWindow(), "Select File", "",
                                                   "All Files (*);;Text Files (*.txt)",
                                                   options=options)
        if file_name:
            self.lineEdit.setText(file_name)
            self.statusbar.showMessage("file path: " + file_name, 5000)

    def gti2tax_on_button_clicked(self):
        self.statusbar.showMessage("GTI -> TAX", 5000)

    def tax2gti_on_button_clicked(self):
        self.statusbar.showMessage("TAX -> GTI", 5000)

    def update_status_bar(self, error_message):
        self.statusbar.showMessage(f'Error: {error_message}', 5000)
import pictures_rc
